### PR TITLE
.travis builds

### PR DESCRIPTION
**Pull request by sfgraves**
This is an updated .travis.yml file, to allow for automated testing on python 2.7, 3.5, 3.6 and 3.7 , and automated binary builds to be pushed to twine if the build passes the test and has a tag. Currently the username in the file is mine, which I'm happy to change if someone else would prefer to have their account there.

I also made a minor change to a test, and added numpy to the setup and install requires.

Someone will also have to approve travis connecting to the Starlink organisation (I'm not an owner so I can't do that). I think there's some more initial  admin on the pypi end as well.

### CODE REVIEW

**Comment by timj** [comment]
@sfgraves I've approved it and also made you an owner.

**Comment by timj** [comment]
Can we drop 2.7 and 3.5? There is no reason in 2020 to support those.

**Comment by sfgraves** [comment]
I'd prefer to keep them until I get more of our local users off 2.7 and 3.5. Most of the science team have switched to 3.5 at least I think, but I'm not sure I've got them to use our 3.7 build yet.

**Comment by dsberry** [comment]
"Someone will also have to approve travis connecting to the Starlink organisation" - doesn't it already do that when it does the tests following the creation of a new pull request?

Regarding the twine username, I suppose it would be more consistent if it was mine ("dsberry"). Where does the password go?

At what point does the extra pypi "initial admin" need to be done? 

If Tim's approved it, presumably all I need to do is press the button to merge the pull request?

**Comment by sfgraves** [comment]
@dsberryIt looks like you can change it to __token__ and use a pypi API token now, which would be better than username/password. You set up the API token as TWINE_PASSWORD in the Travis settings for this specific repo: see this cibuildwheel documentation https://github.com/joerick/cibuildwheel-autopypi-example

You'll need a travis-ci.org account which you link to your Github Account, and then it should show you your available repos to set up, where you can select starlink-pyast.

You also have to upload the source distribution and upload that with twine. You're already the maintainer on pypi, so I'd assume all the permissions/admin on that end are already done. (https://pypi.org/project/starlink-pyast/)

**Comment by dsberry** [comment]
@sfgraves I merged your pull request and then changed the twine login as you suggested. It all seems to be working. It automatically built and uploaded the binaries to pypi for v3.14.4. The only down side is that the time taken to do the travis tests after each commit has jumped from around 5 mins to about 1 hour 10 mins.  But I suppose there's no such thing as a free lunch.

**Pull request merged**
